DROP TABLE IF EXISTS rewards;
DROP TABLE IF EXISTS campaigns;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS city;
DROP TABLE IF EXISTS uf;
DROP TABLE IF EXISTS datasource;
